# Generated by Django 3.2.2 on 2021-11-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.CharField(blank=True, max_length=200, null=True, verbose_name='공연ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('img', models.ImageField(blank=True, upload_to='main/', verbose_name='포스터')),
                ('openDate', models.DateTimeField(blank=True, null=True, verbose_name='예매오픈시간')),
                ('score1', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='넘버점수')),
                ('score2', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='배우점수')),
                ('score3', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='무대점수')),
                ('score4', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='스토리점수')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰수')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_product', to=settings.AUTH_USER_MODEL, verbose_name='담은유저')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('category', models.CharField(choices=[('review', '후기'), ('etc', '잡담'), ('informantion', '정보')], default='top', max_length=100, verbose_name='카테고리')),
                ('text', models.TextField(verbose_name='본문')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('is_review', models.BooleanField(default=False, verbose_name='후기여부')),
                ('is_liked', models.BooleanField(default=False, verbose_name='인기글')),
                ('img', models.ImageField(blank=True, null=True, upload_to='main/')),
                ('liked_user', models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL, verbose_name='스크랩유저')),
                ('tags', models.ManyToManyField(blank=True, related_name='product_tags', to='main.Product', verbose_name='태그')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_post', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='main.post', verbose_name='포스트')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_comment', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
