# Generated by Django 3.2.2 on 2021-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('informantion', '정보'), ('etc', '잡담'), ('review', '후기')], default='top', max_length=100, verbose_name='카테고리'),
        ),
    ]
