# Generated by Django 3.2.2 on 2021-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('review', '후기'), ('etc', '잡담'), ('informantion', '정보')], default='top', max_length=100, verbose_name='카테고리'),
        ),
    ]
