# Generated by Django 4.1 on 2022-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('review', '후기'), ('etc', '잡담'), ('information', '정보')], default='top', max_length=100, verbose_name='카테고리'),
        ),
    ]
